server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: vehiculo-service
          uri: lb://vehiculo-service
          predicates:
            - Path=/api/v1/vehiculo/**
        - id: precio-por-rep-service
          uri: lb://precio-por-rep-service
          predicates:
            - Path=/api/v1/precioPorRep/**
        - id: ingreso-service
          uri: lb://ingreso-service
          predicates:
            - Path=/api/v1/ingresoAReparacion/**
        - id: rdr-ingreso-service
          uri: lb://rdr-ingreso-service
          predicates:
            - Path=/api/v1/repEspecifica/**
        - id: descuentos-service
          uri: lb://descuentos-service
          predicates:
            - Path=/api/v1/descuentos/**
        - id: recargos-service
          uri: lb://recargos-service
          predicates:
            - Path=/api/v1/recargoPorKilometraje/**,/api/v1/recargoPorAntiguedad/**,/api/v1/recargos/**
        - id: bonos-aplicados-service
          uri: lb://bonos-aplicados-service
          predicates:
            - Path=/api/v1/bonoAplicado/**
        - id: reportes-service
          uri: lb://reportes-service
          predicates:
            - Path=/api/v1/reportes/**