server:
  port: ${SERVER_PORT}
spring:
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka/
  